name: space rover app CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: spacerover

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if ([ -f requirements.txt ]) { pip install -r requirements.txt; }

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # - name: Test with pytest
    #   run: |
    #     pytest

    - name: Build exe from Python Script
      uses: Nuitka/Nuitka-Action@v0.4
      with:
        nuitka-version: main
        script-name: spacerover/__main__.py
        onefile: true
        enable-plugins: tk-inter

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: spacerover
        path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
